DjangoProject1/my_template_site_three/my_template_site_three/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_view , name= 'home'),
    path('test_app/', include('test_app.urls'))
]

handler404 = 'my_template_site_three.views.my_custom_error_view_to_handle_404'

DjangoProject1/my_template_site_three/test_app/urls.py
from django.urls import path, include
from . import views

app_name = 'test_app'

urlpatterns = [
    path('', views.example_view, name= 'index'),
    path('variable/', views.variable_view, name= 'variable')
]

DjangoProject1/my_template_site_three/test_app/models.py
from django.db import models

# Create your models here.

DjangoProject1/my_template_site_three/my_template_site_three/views.py
from django.shortcuts import render

def home_view(request) :
    return render(request, 'home.html')

def my_custom_error_view_to_handle_404(request, exception):
    return render(request, 'custom_error.html', status=404)

DjangoProject1/my_template_site_three/test_app/views.py
from django.shortcuts import render

# Create your views here.

def example_view(request) :
    return render(request, 'test_app/example.html')

def variable_view(request) :
    
    my_var = {
        'first_name' : 'BenJamin',
        'last_name' : 'frankLin',
        'some_list' : [0,1,2,3,4,5, 29, 71, 45, 61],
        'some_dict' : { 'inside_key' : 'inside_value'}
    }
    
    return render(request, 'test_app/variable.html', context=my_var)

DjangoProject1/my_template_site_three/my_template_site_three/templates/custom_error.html
{% extends "home.html" %}

{% block main %}
<h1>The requested resource was not found. My 404 message.</h1>
{% endblock main %}

DjangoProject1/my_template_site_three/my_template_site_three/templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>{% block title %} Main page {% endblock title%}</title>
</head>
{% load static %}
<body background="{% static 'test_app/background_view.jpg' %}">

<header>
    <h1 style="color:white;">Home Page</h1>
    {% block header %} {% endblock header %}
</header>

<nav>
    {% block navigation %}
    <ul>
    <!-- <li><p><a href = "/test_app" > Test App Screen</a></p></li> -->
    <li><p><a href = "{% url "test_app:index" %}" style="color:white;">Test App Home Page</a></p></li>
    </ul>
    {% endblock navigation %}
</nav>


<main>

<img src="{% static 'test_app/background_view.jpg' %}" alt = "my image"> 
{% block main %} {% endblock main %}
</main>

<footer> 
    {% block footer %} {% endblock %}
    <p style="color:white;">@Contact Us</p>
</footer>
</body>
</html>

DjangoProject1/my_template_site_three/test_app/templates/test_app/example.html
{% extends "home.html" %}
{% load static %}
{% block title %} TestApp Page {% endblock title %} TestApp Page

{% block header %}
<h1 style="color:white;"> Test App Page</h1>
{% endblock header %}


    {% block navigation %}
    <ul>
    <li><p><a href= "{% url "test_app:variable" %} " style="color:white;">variable screen</a></p></li>
    <li><p><a href = "{% url "home" %}" style="color:white;">Home Page</a></p></li>
    </ul>
    {% endblock navigation %}
    
{% block main %}
<img src="{% static 'test_app/background_view.jpg' %}" alt = "my image"> 
<p style="color:white;">This is the playground for main logic of Test App</p>
{% endblock main %}

{% block footer %}
<p style="color:white;"> This is the end of Test App</p>
{% endblock footer %}

DjangoProject1/my_template_site_three/test_app/templates/test_app/variable.html
{% extends 'test_app\example.html' %} <!--we understood to use this path 
for app level template based on error received on debug screen-->


{% block navigation %}
<ul>
    <li><p><a href = "{% url "test_app:index" %}">Test App Home Page</a></p></li>
    <li><p><a href = "{% url "home" %}">Home Page</a></p></li>
</ul>
{% endblock navigation %}

{% block main %}
    <h1 style="color:white;">Inside variable html</h1>
    <h2 style="color:white;">her first name was {{ first_name | lower | capfirst}} and her last name was {{ last_name  | lower | capfirst}}</h2>
    <h2 style="color:white;">Getting element using index = {{ some_list.0 }}</h2>
    <h2 style="color:white;">Getting key from inside dict = {{ some_dict.inside_key }}</h2>
    <h2>{# comment using django template language #}</h2>
    <!-- html way of commenting -->
    
    <ul style="color:white;">
    {% for item in some_list %}
       {% if item == 0 %}
        <li>{{item}} - its zero</li>
        {% elif item|divisibleby:2%}
        <li>{{item}} - its Even</li>
        {% else %}
        <li>{{item}} - its odd</li>
        
    {% endif %} 
    {%   endfor %}
    </ul>

    <ul style="color:white;">
        {% for k,v in some_dict.items %}
            <li>{{k }} : {{ v}}</li>
        {% endfor %}
    </ul>

{% endblock main %}